// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/prototype/:trialToken": {
    params: {
      "trialToken": string;
    };
  };
  "/my-prototypes": {
    params: {};
  };
  "/observability": {
    params: {};
  };
  "/extensions": {
    params: {};
  };
  "/extensions/:id": {
    params: {
      "id": string;
    };
  };
  "/extensions/:id/:slug": {
    params: {
      "id": string;
      "slug": string;
    };
  };
  "/database": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/catalog": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/agent": {
    params: {};
  };
  "/build": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/chat/:threadId": {
    params: {
      "threadId": string;
    };
  };
  "/team": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/prototype/:trialToken" | "/my-prototypes" | "/observability" | "/extensions" | "/extensions/:id" | "/extensions/:id/:slug" | "/database" | "/settings" | "/catalog" | "/admin" | "/agent" | "/build" | "/chat" | "/chat/:threadId" | "/team";
  };
  "routes/prototype.$trialToken.tsx": {
    id: "routes/prototype.$trialToken";
    page: "/prototype/:trialToken";
  };
  "routes/my-prototypes.tsx": {
    id: "routes/my-prototypes";
    page: "/my-prototypes";
  };
  "routes/observability.tsx": {
    id: "routes/observability";
    page: "/observability";
  };
  "routes/extensions.tsx": {
    id: "routes/extensions";
    page: "/extensions" | "/extensions/:id" | "/extensions/:id/:slug";
  };
  "routes/extensions._index.tsx": {
    id: "routes/extensions._index";
    page: "/extensions";
  };
  "routes/extensions.$id.tsx": {
    id: "routes/extensions.$id";
    page: "/extensions/:id" | "/extensions/:id/:slug";
  };
  "routes/extensions.$id.$slug.tsx": {
    id: "routes/extensions.$id.$slug";
    page: "/extensions/:id/:slug";
  };
  "routes/database.tsx": {
    id: "routes/database";
    page: "/database";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/catalog.tsx": {
    id: "routes/catalog";
    page: "/catalog";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/agent.tsx": {
    id: "routes/agent";
    page: "/agent";
  };
  "routes/build.tsx": {
    id: "routes/build";
    page: "/build";
  };
  "routes/chat.tsx": {
    id: "routes/chat";
    page: "/chat" | "/chat/:threadId";
  };
  "routes/chat.$threadId.tsx": {
    id: "routes/chat.$threadId";
    page: "/chat/:threadId";
  };
  "routes/team.tsx": {
    id: "routes/team";
    page: "/team";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/prototype.$trialToken": typeof import("./app/routes/prototype.$trialToken.tsx");
  "routes/my-prototypes": typeof import("./app/routes/my-prototypes.tsx");
  "routes/observability": typeof import("./app/routes/observability.tsx");
  "routes/extensions": typeof import("./app/routes/extensions.tsx");
  "routes/extensions._index": typeof import("./app/routes/extensions._index.tsx");
  "routes/extensions.$id": typeof import("./app/routes/extensions.$id.tsx");
  "routes/extensions.$id.$slug": typeof import("./app/routes/extensions.$id.$slug.tsx");
  "routes/database": typeof import("./app/routes/database.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/catalog": typeof import("./app/routes/catalog.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/agent": typeof import("./app/routes/agent.tsx");
  "routes/build": typeof import("./app/routes/build.tsx");
  "routes/chat": typeof import("./app/routes/chat.tsx");
  "routes/chat.$threadId": typeof import("./app/routes/chat.$threadId.tsx");
  "routes/team": typeof import("./app/routes/team.tsx");
};